apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: shopper
  namespace: t20
spec:
  hosts:
    - "*"
  gateways:
    - shopper-gateway
  http:
    - route:
        - destination:
            host: shopper
            port:
              number: 8080
            subset: v1
          weight: 50
        - destination:
            host: shopper
            port:
              number: 8080
            subset: v2
          weight: 50
